#!/bin/bash -e

availability_zones=`aws ec2 describe-availability-zones | jq -r .AvailabilityZones[].ZoneName | head -3 | paste -sd "," -`

cat <<EOF > terraform.tfvars
cidr = {
  availability_zones = "${availability_zones}"
}
EOF
